### ISSUE TITLE
CRUD produkty

### ISSUE THREAD

**Issue by Delebrith** [Delebrith/ShoppingM8-client#15]
CRUD + autocomplete. Update uwzględnia konflikt edycji. Tabelka jednostek + endpoint R. Tabelka kategorii + endpoint R

**Comment by Delebrith** [comment]
prośba, aby ścieżka wyglądała następująco /list/{list_id}/product dla wszystkich produktów oraz /list/{list_id}/product/{product_id} dla poszczególnych

**Comment by lychanl** [comment]
proponuje ścieżki /product/unit/all na jednostki i /product/category/all na kategorie
oraz /product/unit/{id} i /product/category/{id} na pojedyncze obiekty

**Comment by Delebrith** [comment]
Ja bym proponowała zarzucić na razie pomysł z tabelką i zrobić enum na kategorię i pole typu String na jednostkę. Będzie szybciej, o konfigurowalność na razie się nie martwmy.

**Comment by lychanl** [comment]
Już właściwie mam tę część taska zrobioną po stronie backendu, wystarczy mi informacja czy te propozycje endpointów są OK - alternatywnie mogę zmienić na enumy
